// react-client/src/ui/pages/Booking.tsx
import { useEffect, useMemo, useState } from 'react'
import { useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { api } from '../../api'

type Slot = { id: number; start: string; end: string; available: boolean }

export default function Booking() {
  const { machineId } = useParams()
  const mId = Number(machineId)
  const [params] = useSearchParams()
  const preSlotId = Number(params.get('slotId') || '')
  const [date, setDate] = useState<string>('')
  const [slots, setSlots] = useState<Slot[]>([])
  const [selected, setSelected] = useState<number | null>(preSlotId || null)
  const [err, setErr] = useState<string>('')
  const [loading, setLoading] = useState(false)
  const [booking, setBooking] = useState(false)
  const navigate = useNavigate()

  useEffect(() => {
    const today = new Date()
    const y = today.getFullYear()
    const m = String(today.getMonth() + 1).padStart(2, '0')
    const d = String(today.getDate()).padStart(2, '0')
    const t = `${y}-${m}-${d}`
    setDate(t)
  }, [])

  useEffect(() => {
    if (!mId || !date) return
    let rolledOnce = false
    async function load() {
      setLoading(true)
      setErr('')
      try {
        const s = await api.getSlots(mId, date)
        // if today and none available, auto roll to next day once (match Vue behavior)
        const today = new Date().toISOString().slice(0, 10)
        if (!rolledOnce && date === today && s.every((x: any) => !x.available)) {
          const next = new Date(date)
          next.setDate(next.getDate() + 1)
          const nextStr = next.toISOString().slice(0, 10)
          setDate(nextStr)
          rolledOnce = true
          const s2 = await api.getSlots(mId, nextStr)
          setSlots(s2)
          alert('今日已无可预约时段，已切换到明天')
        } else {
          setSlots(s)
        }
      } catch (e: any) {
        setErr(e?.message || '加载失败')
      } finally {
        setLoading(false)
      }
    }
    load()
  }, [mId, date])

  async function submit() {
    setErr('')
    try {
      if (!selected) throw new Error('请选择时段')
      setBooking(true)
      await api.createReservation({ machineId: mId, slotId: selected, date })
      navigate('/my')
    } catch (e: any) {
      setErr(e.message || '预约失败')
    } finally {
      setBooking(false)
    }
  }

  const daySlots = useMemo(() => slots, [slots])

  return (
    <div>
      <h2>预约</h2>
      <div className="row">
        <label>
          <span>日期</span>
          <input type="date" value={date} onChange={e => setDate(e.target.value)} />
        </label>
      </div>
      {loading && <p>加载时段中...</p>}
      {err && <p className="err">{err}</p>}
      {!loading && (
        <ul className="slots">
          {daySlots.map(s => (
            <li key={s.id}>
              <label>
                <input type="radio" name="slot" disabled={!s.available} checked={selected === s.id} onChange={() => setSelected(s.id)} />
                {s.start} - {s.end}
                {!s.available && <span className="full">已满</span>}
              </label>
            </li>
          ))}
        </ul>
      )}
      <button className="primary" disabled={!selected || booking} onClick={submit}>{booking ? '提交中...' : '确认预约'}</button>
    </div>
  )
}

// client/src/pages/Booking.vue
<template>
	<section>
		<h2>预约时间</h2>
		<div class="row">
			<label>
				<span>日期</span>
				<input type="date" v-model="date" @change="onDateChange" />
			</label>
		</div>
		<p v-if="loading">加载时段中...</p>
		<p v-if="error" class="err">{{ error }}</p>
		<ul v-if="!loading" class="slots">
			<li v-for="s in slots" :key="s.id">
				<label>
					<input type="radio" name="slot" :value="s.id" v-model="selectedSlotId" :disabled="!s.available" />
					{{ s.start }} - {{ s.end }}
					<span v-if="!s.available" class="full">已满</span>
				</label>
			</li>
		</ul>
		<button class="primary" :disabled="!selectedSlotId || booking" @click="book">{{ booking ? '提交中...' : '确认预约' }}</button>
	</section>
</template>

<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { api } from '../services/api'
import { useAuthStore } from '../stores/auth'

const route = useRoute()
const router = useRouter()
const auth = useAuthStore()
const machineId = Number(route.params.machineId)

interface Slot { id: number; start: string; end: string; available: boolean }
const slots = ref<Slot[]>([])
const selectedSlotId = ref<number | null>(null)
const loading = ref(false)
const error = ref('')
const booking = ref(false)
const date = ref<string>(new Date().toISOString().slice(0, 10))
let rolledOnce = false

function isToday(iso: string) {
	const now = new Date()
	const d = new Date(iso)
	return now.getFullYear() === d.getFullYear() && now.getMonth() === d.getMonth() && now.getDate() === d.getDate()
}

async function loadSlots() {
	loading.value = true
	error.value = ''
	try {
		slots.value = await api.getSlots(machineId, date.value)
		// if today and none available, auto roll to next day once
		if (!rolledOnce && isToday(date.value) && slots.value.every(s => !s.available)) {
			const next = new Date(date.value)
			next.setDate(next.getDate() + 1)
			date.value = next.toISOString().slice(0, 10)
			rolledOnce = true
			await loadSlots()
			alert('今日已无可预约时段，已切换到明天')
			return
		}
	} catch (e: any) {
		error.value = e?.message || '加载失败'
	} finally {
		loading.value = false
	}
}

function onDateChange() {
	selectedSlotId.value = null
	rolledOnce = false
	loadSlots()
}

onMounted(() => {
	const qd = route.query.date as string | undefined
	if (qd) date.value = qd
	loadSlots()
})

watch(() => route.query.date, (val) => {
	if (typeof val === 'string' && val) {
		date.value = val
		onDateChange()
	}
})

async function book() {
	if (!selectedSlotId.value) return
	booking.value = true
	try {
		await api.createReservation({ machineId, slotId: selectedSlotId.value, date: date.value })
		alert('预约成功')
		router.push({ name: 'my' })
	} catch (e: any) {
		alert(e?.message || '提交失败')
	} finally {
		booking.value = false
	}
}
</script>

<style scoped>
.row { display: flex; gap: 8px; margin-bottom: 10px; }
.slots { list-style: none; padding: 0; }
.slots li { margin-bottom: 8px; }
.full { color: #ef4444; margin-left: 8px; }
.primary { margin-top: 12px; background: #2563eb; color: white; padding: 8px 12px; border: 0; border-radius: 6px; cursor: pointer; }
.err { color: #ef4444; }
</style>
